### ISSUE TITLE
Reset cyrilic encoding

### ISSUE THREAD

**Issue by Kasseopey** [exeldro/obs-markdown#2]
Hello! 

I use the Cyrillic layout.
The source does not matter (text or file)
Every time you start the OBS, the encoding “breaks”.
But if you make a change to the text (even a “space”), the encoding immediately becomes correct
When you restart the application, the encoding breaks again
I tried changing the file encoding manually - it didn't help (UTF-8, KOI8-R, Win-1251)

![2023-12-05_23-31-43](https://github.com/exeldro/obs-markdown/assets/16265702/5dcffbe2-9015-4c4d-bab3-cc2ca855efa1)

**Comment by exeldro** [comment]
I made a fix, can you you test if the build on the bottom of [this page](https://github.com/exeldro/obs-markdown/actions/runs/7113086511) fixes it for you?

**Comment by Kasseopey** [comment]
> I made a fix, can you you test if the build on the bottom of [this page](https://github.com/exeldro/obs-markdown/actions/runs/7113086511) fixes it for you?

Yes, is fixed!
I test it with different sources, and type of files - now its work correctly.
Thank you!

![2023-12-08_00-24-11](https://github.com/exeldro/obs-markdown/assets/16265702/2948b545-bb8e-470d-850b-1324e2cd8ce6)
