### ISSUE TITLE
[BUG] Background color doesn't work, text size in markdown table is not displayed correctly

### ISSUE THREAD

**Issue by ZRdRy** [exeldro/obs-markdown#7]
Markdown Source version 0.2.5 doesn't seem to work with background color in OBS 30.2.3, and the font size in the markdown table doesn't display correctly.​

**Comment by exeldro** [comment]
What markdown did you use? What did you expect to display? What did it display?

**Comment by ZRdRy** [comment]
> What markdown did you use? What did you expect to display? What did it display?

![PixPin_2024-11-10_17-57-32](https://github.com/user-attachments/assets/280857d5-62bf-4f0a-8629-501993d11513)

I don't know if it's my wrong way of using it or there is a bug, when I choose the background color it doesn't take effect, after inputting markdown text to adjust the text size only the title or normal input text takes effect, the text size inside the markdown table doesn't take effect.

**Comment by exeldro** [comment]
The background color you selected has alpha channel set to 0 which makes it fully transparent, set it to 255 to see the color.
The font size in a table was indeed not the selected size, I made a fix, the test build you download from the bottom of this page:
https://github.com/exeldro/obs-markdown/actions/runs/11766564343

**Comment by ZRdRy** [comment]
> The background color you selected has alpha channel set to 0 which makes it fully transparent, set it to 255 to see the color. The font size in a table was indeed not the selected size, I made a fix, the test build you download from the bottom of this page: https://github.com/exeldro/obs-markdown/actions/runs/11766564343

Thanks, I adjusted the alpha, It's showing up, the text size in the markdown table is normal in the test version
